defmodule PPM do

  # write(name, image) The image is a list of rows, each row a list of
  # tuples {R,G,B}. The RGB values are 0-255.
  def write(name, image) do
    [foldername | _] = String.split(name, "s")
    height = length(image)
    width = length(List.first(image))
    {:ok, fd} = File.open("./ppms/#{foldername}/#{name}.ppm", [:write])
    IO.puts(fd, "P6")
    IO.puts(fd, "#generated by ppm.ex")
    IO.puts(fd, "#{width} #{height}")
    IO.puts(fd, "255")
    rows(image, fd)
    File.close(fd)
    name = String.replace(name, ~r/[pm]/, "")
    System.cmd("magick", ["convert", "./ppms/#{foldername}/#{name}.ppm", "./images/#{foldername}/#{name}.png"])
  end

  defp rows(rows, fd) do
    Enum.each(rows, fn(r) -> colors = row(r); IO.write(fd, colors) end)
  end

  defp row(row) do
    List.foldr(row, [], fn({:rgb, r, g, b}, acc) -> [r, g, b | acc] end)
  end
end